language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - ruby-head
  - jruby-head
script: bundle exec rake test
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head
